"""Change close date sielld

Revision ID: c6344d6c51a2
Revises: 480c75b9351c
Create Date: 2023-10-18 11:56:32.742929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6344d6c51a2'
down_revision = '480c75b9351c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
